micronaut:
  server:
    idle-timeout: 30m
    cors:
      enabled: true
    netty:
      worker:
        event-loop-group: other
  netty:
    event-loops:
      other:
        num-threads: 10
  http:
    client:
      read-idle-timeout: 30m
  io:
    watch:
      paths: src/main
      restart: true
  application:
    name: mock
  executors:
    io:
      type: fixed
      n-threads: 75
    consumer:
      type: fixed
  security:
    enabled: true
  endpoints:
    routes:
      enabled: Boolean
      sensitive: Boolean

datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost:5432/mock`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME:`bdurdu`}
    password: ${DB_PASSWORD:`''`}
    schema-generate: CREATE_DROP
    dialect: POSTGRES
    logSql: true

jpa:
  default:
    entity-scan:
      packages:
        - 'com.pow.models'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true